name: 'Create a PR based on validation'

on: 
    workflow_dispatch: {} 

jobs:
  repolinter-action:
    runs-on: ubuntu-latest
    name: Run Repolinter
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: 'Run Repolinter'
        uses: DSACMS/repolinter-action@main
        with:
          output_type: 'pull-request'
          labels: 'repolinter, OSPO, Tier 1'