name: Test New Repolinter Action
on:
    push:   
    workflow_dispatch: {} 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
      
      - name: Test Local Action
        uses: sachin-panayil/repolinter-action@main 
        with:
          output_type: 'pull-request'  


